import Layout from "../components/Layout";
import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Avatar from "../../public/images/profile/Avatar.png";
import AnimatedText from "../components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "../components/Icons";
import HireMe from "../components/HireMe";
import TransitionEffect from "../components/TransitionEffect";
import { TypeAnimation } from "react-type-animation";
import {
  HeroContainer,
  HeroWrapper,
  HeroLeft,
  HeroRight,
  ScrollDown,
  ScrollLink,
} from "../components/CssElements";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const [showSubtitle, setShowSubtitle] = useState(false);
  const [showScrollDown, setShowScrollDown] = useState(false);

  const toggle = () => {
    setIsOpen(!isOpen);
  };
  return (
    <>
      <Head>
        <title>Sneha Sahu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />
      <main className="flex items-center w-full min-h-screen  text-dark dark:text-light">
        <Layout className="py-28 sm:pt-28">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/3 md:w-1/2">
              <Image
                src={Avatar}
                alt="Sneha Sahu Avatar"
                className="w-full h-auto  md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw
                        (max-width: 1200px) 50vw
                        50vw"
              />
            </div>
            <div className="w-[55%] flex flex-col lg:items-center items-start self-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Hello!"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <AnimatedText
                text="I'm Sneha Sahu"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <div className="!text-3xl  sm:!text-xl">
                <TypeAnimation
                  cursor={true}
                  sequence={[
                    500,
                    "A Frontend Developer.",
                    1000,
                    "A Full-Stack Developer.",
                    1000,
                    "A BTech undergraduate.",
                    1000,
                    " A problem solver.",
                    1000,
                    "A....",
                    1000,
                    "A.... cool person?",
                    1000,
                    "Ok...",
                    1000,
                    "Ok...  I'm running out of ideas...",
                    1000,
                    "Uhh...",
                    1000,
                    "Uhh... you can go ahead to see my projects now...",
                    300,
                    () => setShowScrollDown(true),
                    1000,
                    "Seriously, my projects are really cool, go check them out!",
                    1000,
                    "You're uh...",
                    1000,
                    "You're uh... still here?",
                    1000,
                    "Ok, this has been fun, but I'm gonna restart the loop now...",
                    // 1000,
                    // "Or...",
                    // 1000,
                    // "Or... I could scroll you by force! Muahaha!",
                    1000,
                    "See ya! :)",
                    500,
                  ]}
                  speed={50}
                  deletionSpeed={65}
                  wrapper="h5"
                  repeat={Infinity}
                />
              </div>
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled Full Stack Developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise using MERN stack.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Sneha_Sahu_Resume.pdf"
                  target="_blank"
                  className="flex items-center  p-2.5 px-6 text-lg rounded-lg font-semibold 
               border-2 border-solid border-transparent bg-dark text-light hover:text-dark hover:border-dark hover:bg-light
              dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:s.sneha1712@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg md:text-base capitalize underline font-medium text-dark dark:text-light "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
