import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profile2 from "../../public/images/profile/profile2.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/3 md:w-1/2">
              <Image
                src={profile2}
                alt="Sneha Sahu Avatar"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw
                        (max-width: 1200px) 50vw
                        50vw"
              />
            </div>
            <div className="w-[55%] flex flex-col items-center self-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled Frontend Developer, I am dedicated to turning ideas
                into innovative web applications. Explore my latest projects and
                articles, showcasing my expertise in React.js and Frontend
                development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/121CE1045_SNEHA.pdf"
                  target="_blank"
                  className="flex items-center  p-2.5 px-6 text-lg rounded-lg font-semibold 
               border-2 border-solid border-transparent bg-dark text-light hover:text-dark hover:border-dark hover:bg-light
              dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download
                >
                  Resume <LinkArrow className={'w-6 ml-1'}/>
                </Link>
                <Link href="mailto:s.sneha1712@gmail.com" target="_blank" className="ml-4 text-lg md:text-base capitalize underline font-medium text-dark dark:text-light ">
                  Contact
                </Link>
                
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
      </main>
    </>
  );
}
