
export const CarouselData = [
    {
      image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507706/airbnb_k6ihcv.png",
    },
    {
      image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507777/api-store_dqiege.png",
    },
    {
        image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507792/dummy-portfolio_zvh3l0.png",
    },
    {
        image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507800/weather_jgh8ow.png",
    },
    {
      image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507495/maze_xodqxa.png",
    },
    {
      image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507499/typing-test_mtgqlt.png",
    },
    {
      image:
        "https://res.cloudinary.com/dkqxnquga/image/upload/v1680507492/to-do_qhgj68.png",
    },
  ];